"""
Recovery workflow models for RevRecover.

This module contains the core entities used to control and track
revenue recovery workflows.

Recovery policies define the boundaries of what the recovery system
is allowed to do. Recovery cases represent individual recovery
workflows, while recovery actions and attempts track what the system
plans and executes.
"""

import uuid
from datetime import datetime, timezone
from decimal import Decimal

from sqlalchemy import Boolean, DateTime, ForeignKey, Integer, Numeric, String, Text
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base


def utc_now() -> datetime:
    """Return the current UTC datetime."""
    return datetime.now(timezone.utc)


class RecoveryPolicy(Base):
    """
    Define the rules and safety boundaries for recovery workflows.

    A recovery policy limits what RevRecover can do when attempting
    to recover a failed or at-risk payment. Policies prevent the AI
    system from acting with unrestricted authority.

    Attributes:
        id: Unique UUID identifying the policy.
        organisation_id: UUID of the organisation owning the policy.
        name: Human-readable policy name.
        max_attempts: Maximum number of recovery attempts permitted.
        min_hours_between_attempts: Minimum delay between attempts.
        max_recovery_amount: Maximum amount that can be recovered
            under this policy.
        allowed_channels: Communication channels permitted by the policy.
        allow_discount: Whether discounts may be offered.
        require_approval_above: Amount above which human approval is required.
        stop_after_success: Whether recovery should stop after success.
        is_active: Whether this policy is currently active.
        created_at: Timestamp when the policy was created.
        updated_at: Timestamp when the policy was last updated.
    """

    __tablename__ = "recovery_policies"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )

    organisation_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("organisations.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    name: Mapped[str] = mapped_column(String(255), nullable=False)

    max_attempts: Mapped[int] = mapped_column(Integer, nullable=False, default=3)

    min_hours_between_attempts: Mapped[int] = mapped_column(
        Integer, nullable=False, default=24
    )

    max_recovery_amount: Mapped[Decimal | None] = mapped_column(
        Numeric(15, 2), nullable=True
    )

    allowed_channels: Mapped[list] = mapped_column(JSONB, nullable=False, default=list)

    allow_discount: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)

    require_approval_above: Mapped[Decimal | None] = mapped_column(
        Numeric(15, 2), nullable=True
    )

    stop_after_success: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=True
    )

    is_active: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=utc_now,
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=utc_now, onupdate=utc_now
    )


class RecoveryCase(Base):
    """
    Represent a revenue recovery workflow for a payment.

    A recovery case is created when RevRecover identifies a payment
    that may be recoverable. It tracks the case throughout analysis,
    planning, execution, waiting, recovery, failure, or escalation.

    The case also stores the risk assessment and recovery probability
    generated by the recovery decision system.

    Attributes:
        id: Unique UUID identifying the recovery case.
        organisation_id: UUID of the organisation.
        customer_id: UUID of the affected customer.
        payment_id: UUID of the payment being recovered.
        policy_id: UUID of the policy governing this case.
        risk_amount: Amount considered at risk.
        risk_type: Category of the recovery risk.
        failure_reason: Reason associated with the payment failure.
        failure_code: Provider-specific failure code.
        risk_score: Calculated risk score for the payment.
        recovery_probability: Estimated probability of successful recovery.
        status: Current state of the recovery workflow.
        current_step: Current workflow step.
        max_attempts: Maximum recovery attempts permitted for this case.
        started_at: Timestamp when recovery processing started.
        stopped_at: Timestamp when recovery processing stopped.
        recovered_at: Timestamp when the payment was recovered.
        recovered_amount: Amount successfully recovered.
        created_at: Timestamp when the case was created.
        updated_at: Timestamp when the case was last updated.
    """

    __tablename__ = "recovery_cases"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )

    organisation_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("organisations.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    customer_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("customers.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    payment_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("payments.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    policy_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("recovery_policies.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )

    risk_amount: Mapped[Decimal] = mapped_column(Numeric(15, 2), nullable=False)

    risk_type: Mapped[str] = mapped_column(String(100), nullable=False)

    failure_reason: Mapped[str | None] = mapped_column(String(500), nullable=True)

    failure_code: Mapped[str | None] = mapped_column(String(100), nullable=True)

    risk_score: Mapped[Decimal | None] = mapped_column(Numeric(5, 2), nullable=True)

    recovery_probability: Mapped[Decimal | None] = mapped_column(
        Numeric(5, 2), nullable=True
    )

    status: Mapped[str] = mapped_column(
        String(50), nullable=False, default="detected", index=True
    )

    current_step: Mapped[str | None] = mapped_column(String(100), nullable=True)

    max_attempts: Mapped[int] = mapped_column(Integer, nullable=False, default=3)

    started_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    stopped_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    recovered_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    recovered_amount: Mapped[Decimal | None] = mapped_column(
        Numeric(15, 2), nullable=True
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=utc_now
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=utc_now, onupdate=utc_now
    )


class RecoveryAction(Base):
    """
    Represent an action planned or executed for a recovery case.

    A recovery action describes what RevRecover intends to do,
    such as sending a payment reminder, retrying a payment, or
    requesting human approval.

    Attributes:
        id: Unique UUID identifying the action.
        recovery_case_id: UUID of the associated recovery case.
        action_type: Type of recovery action.
        status: Current status of the action.
        step_number: Position of the action within the recovery workflow.
        planned_at: Timestamp when the action was planned.
        executed_at: Timestamp when the action was executed.
        created_at: Timestamp when the action record was created.
    """

    __tablename__ = "recovery_actions"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )

    recovery_case_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("recovery_cases.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    action_type: Mapped[str] = mapped_column(String(100), nullable=False)

    status: Mapped[str] = mapped_column(
        String(50), nullable=False, default="planned", index=True
    )

    step_number: Mapped[int] = mapped_column(Integer, nullable=False)

    planned_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    executed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=utc_now
    )


class RecoveryAttempt(Base):
    """
    Represent an individual attempt to execute a recovery action.

    Recovery attempts provide an execution-level record of the
    recovery workflow. They can be used to track the communication
    channel, result, errors, and timing of each recovery attempt.

    Attributes:
        id: Unique UUID identifying the recovery attempt.
        recovery_case_id: UUID of the associated recovery case.
        recovery_action_id: UUID of the action being attempted.
        attempt_number: Sequential number of this recovery attempt.
        channel: Communication or recovery channel used.
        status: Current status of the attempt.
        error_message: Error information when execution fails.
        attempted_at: Timestamp when the attempt was executed.
        created_at: Timestamp when the attempt record was created.
    """

    __tablename__ = "recovery_attempts"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )

    recovery_case_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("recovery_cases.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    recovery_action_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("recovery_actions.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )

    attempt_number: Mapped[int] = mapped_column(Integer, nullable=False)

    channel: Mapped[str | None] = mapped_column(String(50), nullable=True)

    status: Mapped[str] = mapped_column(
        String(50), nullable=False, default="pending", index=True
    )

    error_message: Mapped[str | None] = mapped_column(Text, nullable=True)

    attempted_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=utc_now
    )
