ACTION_RETRY_PAYMENT = "RETRY_PAYMENT"
ACTION_CREATE_PAYMENT_LINK = "CREATE_PAYMENT_LINK"
ACTION_SEND_EMAIL = "SEND_EMAIL"
ACTION_HUMAN_APPROVAL = "HUMAN_APPROVAL"
ACTION_WAIT = "WAIT"
ACTION_STOP = "STOP"

STATUS_PLANNED = "planned"
STATUS_PENDING_APPROVAL = "pending_approval"
STATUS_EXECUTED = "executed"
STATUS_FAILED = "failed"

ALLOWED_AI_ACTIONS = {
    "RETRY",
    "RETRY_AFTER_DELAY",
    "CREATE_PAYMENT_LINK",
    "SEND_PAYMENT_REMINDER",
    "REQUEST_PAYMENT_METHOD_UPDATE",
    "WAIT",
    "ESCALATE",
    "STOP",
    ACTION_RETRY_PAYMENT,
    ACTION_CREATE_PAYMENT_LINK,
    ACTION_SEND_EMAIL,
    ACTION_HUMAN_APPROVAL,
    ACTION_WAIT,
    ACTION_STOP,
}


RECOVERY_STATUSES = {
    "detected",
    "analyzing",
    "planned",
    "awaiting_approval",
    "executing",
    "waiting",
    "recovered",
    "failed",
    "escalated",
    "stopped",
}


RETRYABLE_FAILURE_CODES = {
    "INSUFFICIENT_FUNDS",
    "TEMPORARY_ERROR",
    "BANK_ERROR",
    "NETWORK_ERROR",
    "GATEWAY_ERROR",
}


NON_RETRYABLE_FAILURE_CODES = {"INVALID_CARD", "EXPIRED_CARD", "CARD_NOT_SUPPORTED"}
