import { FailedPayment } from "@/types/payment";

const mockFailedPayments: FailedPayment[] = [
  {
    id: "pay_123",
    customerName: "Rahul Sharma",
    customerEmail: "rahul@example.com",
    amount: 4500,
    currency: "INR",
    failureReason: "Insufficient Funds",
    status: "failed",
    recoveryEligibility: "high",
    failedAt: "2026-08-23T10:42:00Z",
    previousAttempts: 2,
  },
  {
    id: "pay_124",
    customerName: "Aman Verma",
    customerEmail: "aman@example.com",
    amount: 2100,
    currency: "INR",
    failureReason: "Expired Card",
    status: "failed",
    recoveryEligibility: "high",
    failedAt: "2026-08-23T09:18:00Z",
    previousAttempts: 1,
  },
  {
    id: "pay_125",
    customerName: "Priya Mehta",
    customerEmail: "priya@example.com",
    amount: 8900,
    currency: "INR",
    failureReason: "Bank Decline",
    status: "failed",
    recoveryEligibility: "medium",
    failedAt: "2026-08-22T18:32:00Z",
    previousAttempts: 3,
  },
  {
    id: "pay_126",
    customerName: "Arjun Kapoor",
    customerEmail: "arjun@example.com",
    amount: 1200,
    currency: "INR",
    failureReason: "Technical Error",
    status: "failed",
    recoveryEligibility: "high",
    failedAt: "2026-08-22T16:05:00Z",
    previousAttempts: 1,
  },
  {
    id: "pay_127",
    customerName: "Neha Singh",
    customerEmail: "neha@example.com",
    amount: 6700,
    currency: "INR",
    failureReason: "Insufficient Funds",
    status: "failed",
    recoveryEligibility: "high",
    failedAt: "2026-08-22T14:41:00Z",
    previousAttempts: 2,
  },
  {
    id: "pay_128",
    customerName: "Vikram Patel",
    customerEmail: "vikram@example.com",
    amount: 3500,
    currency: "INR",
    failureReason: "Bank Decline",
    status: "failed",
    recoveryEligibility: "medium",
    failedAt: "2026-08-22T12:20:00Z",
    previousAttempts: 2,
  },
  {
    id: "pay_129",
    customerName: "Ananya Gupta",
    customerEmail: "ananya@example.com",
    amount: 980,
    currency: "INR",
    failureReason: "Expired Card",
    status: "failed",
    recoveryEligibility: "high",
    failedAt: "2026-08-21T20:14:00Z",
    previousAttempts: 1,
  },
  {
    id: "pay_130",
    customerName: "Rohan Malhotra",
    customerEmail: "rohan@example.com",
    amount: 11200,
    currency: "INR",
    failureReason: "Technical Error",
    status: "failed",
    recoveryEligibility: "high",
    failedAt: "2026-08-21T17:56:00Z",
    previousAttempts: 1,
  },
];

export async function getFailedPayments(): Promise<FailedPayment[]> {
  return mockFailedPayments;
}
